# Generated by Django 3.1.14 on 2022-06-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='ism')),
                ('lname', models.CharField(max_length=200, verbose_name='familiya')),
                ('gender', models.BooleanField(verbose_name='Jins')),
                ('birth_date', models.DateField(verbose_name='Tugilgan sana')),
                ('address', models.CharField(max_length=500, verbose_name='yashash manzili')),
                ('pass_data', models.CharField(max_length=11, verbose_name='passport')),
                ('pass_end_date', models.DateField(verbose_name='passport amal qilish muddati')),
                ('photo', models.FileField(upload_to='media/anketa', verbose_name='Fotosurat')),
                ('edu_grade', models.CharField(max_length=300, verbose_name='talim daraja')),
                ('fam_state', models.CharField(max_length=300, verbose_name='oilaviy xolat')),
                ('code', models.CharField(max_length=100)),
                ('fill_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='ism')),
                ('lname', models.CharField(max_length=200, verbose_name='familiya')),
                ('gender', models.BooleanField(verbose_name='Jins')),
                ('birth_date', models.DateField(verbose_name='Tugilgan sana')),
                ('address', models.CharField(max_length=500, verbose_name='yashash manzili')),
                ('pass_data', models.CharField(max_length=11, verbose_name='passport')),
                ('pass_end_date', models.DateField(verbose_name='passport amal qilish muddati')),
                ('photo', models.FileField(upload_to='media/anketa', verbose_name='Fotosurat')),
                ('edu_grade', models.CharField(max_length=300, verbose_name='talim daraja')),
                ('fam_state', models.CharField(max_length=300, verbose_name='oilaviy xolat')),
                ('code', models.CharField(max_length=100)),
                ('fill_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, verbose_name='ism')),
                ('lname', models.CharField(max_length=200, verbose_name='familiya')),
                ('gender', models.BooleanField(verbose_name='Jins')),
                ('birth_date', models.DateField(verbose_name='Tugilgan sana')),
                ('address', models.CharField(max_length=500, verbose_name='yashash manzili')),
                ('fam_anket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.familar')),
            ],
        ),
    ]
