# Generated by Django 3.1.14 on 2022-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220629_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familar',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
