# Generated by Django 3.1.14 on 2022-06-30 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220629_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fam_anket',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Familar',
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
