# Generated by Django 3.1.14 on 2022-06-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_anketa_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='type_anketa',
        ),
        migrations.AddField(
            model_name='anketa',
            name='is_pesonal',
            field=models.CharField(default=True, max_length=100, verbose_name='turi'),
        ),
    ]
