# Generated by Django 3.1.14 on 2022-06-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220630_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='is_pesonal',
            field=models.BooleanField(default=True, verbose_name='shaxsiymi?'),
        ),
    ]
