# Generated by Django 3.1.14 on 2022-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220630_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='phone',
            field=models.CharField(default=1, max_length=13, verbose_name='telefon raqam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.FileField(default=None, upload_to='media/anketa', verbose_name='Fotosurat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anketa',
            name='gender',
            field=models.BooleanField(verbose_name='erkakmi?'),
        ),
    ]
