# Generated by Django 3.1.14 on 2022-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220630_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anketa',
            old_name='is_pesonal',
            new_name='is_pesronal',
        ),
        migrations.AlterField(
            model_name='anketa',
            name='pass_data',
            field=models.CharField(max_length=11, unique=True, verbose_name='passport'),
        ),
    ]
